// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA6kqctYoqi9tQ_Qmy7a4lQbzOrTBLr60',
    appId: '1:556724769927:web:7f4cb60f4fcdedb11cd422',
    messagingSenderId: '556724769927',
    projectId: 'grimorio-416b6',
    authDomain: 'grimorio-416b6.firebaseapp.com',
    storageBucket: 'grimorio-416b6.firebasestorage.app',
    measurementId: 'G-ZC66L5D1Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP5rDzWhZq9N9ZkVur7l8PAV81y4XlpD8',
    appId: '1:556724769927:android:1a9eb2dff47ca9581cd422',
    messagingSenderId: '556724769927',
    projectId: 'grimorio-416b6',
    storageBucket: 'grimorio-416b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnRFUERLU_j13LIoyIU50-bgi97u7kahE',
    appId: '1:556724769927:ios:b2a59d9bb6e4190b1cd422',
    messagingSenderId: '556724769927',
    projectId: 'grimorio-416b6',
    storageBucket: 'grimorio-416b6.firebasestorage.app',
    iosBundleId: 'com.example.grimorioNovo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnRFUERLU_j13LIoyIU50-bgi97u7kahE',
    appId: '1:556724769927:ios:b2a59d9bb6e4190b1cd422',
    messagingSenderId: '556724769927',
    projectId: 'grimorio-416b6',
    storageBucket: 'grimorio-416b6.firebasestorage.app',
    iosBundleId: 'com.example.grimorioNovo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA6kqctYoqi9tQ_Qmy7a4lQbzOrTBLr60',
    appId: '1:556724769927:web:6804a6a6502f75691cd422',
    messagingSenderId: '556724769927',
    projectId: 'grimorio-416b6',
    authDomain: 'grimorio-416b6.firebaseapp.com',
    storageBucket: 'grimorio-416b6.firebasestorage.app',
    measurementId: 'G-4RS0G2B9NM',
  );
}
